# THE PROBLEM STATEMENT IS TO FIND THE PRODUCT OF ALL THE VALUES IN THE ARRAY AND THEN RETURN 1 OR 0 OR -1, IF IT IS EITHER A POSITIVE OR ZERO OR NEGATIVE
# VALUE RESPECTIVELY.

# THE APPROACH IS PRETTY STRAIGHT FORWARD, WE HAVE TO FIND THEPRODUCT OD THE ARRAY AND CHECK WHETHER THE VALUE IS EITHER POSITIVE, ZERO OR NEGATIVE.

# IF THE CONSTRAINT IS ON THE HIGHER END, WE HAVE TO RECONSIDER THE APPROACH.\

# THE SECOND APPROACH IS TO COUNT THE NUMBER OF NEGATIVE, POSITIVE AND ZERO VALUE. IF THERE IS ANY ZERO VALUE THEN WE MUST RETURN ZERO, ELSE
# IF CHECK FOR THE NUMBER OF NEGATIVE VALUES, IF IT IS EVEN OR ZERO,THEN RETURN 1 ELSE RETURN -1.

class Solution(object):
    def arraySign(self, nums):
        product = 1
        
        for i in nums:
            product *= i
        
        if(product == 0):
            return 0
        elif(product > 0):
            return 1
        else:
            return -1
        
# TIME COMPLEXITY : O(N)
# SPACE COMPLEXITY : O(1)
