-- THE PROBLEM STATEMNET IS TO QUERY THE NAME,POPULATION AND AREA OF A BIG COUNTRY FROM THE GIVEN TABLE WORLD.
-- A COUNTRY IS BIG IF IT HAS AREA OF BIGGER THAN 3 MILLION SQUARE KM OR A POPULATION OF MAORE THAN 25 MILLION.

SELECT name,population,area FROM World WHERE area > 3000000 OR population > 25000000;
