// THE PROBLEM STATEMENT IS TO RETURN THE PRODUCT OF TWO COMPLEX NUMBERS.
// A COMPLEX NUMBER IS REPRESENTED BY "REAL+(IMAGINARY*I)". (I.E) I*I = -1. 

// MY APPROACH IS TO USE THE SSCANf AND SPRINTF FUNCTION IN C TO GET THE REAL AND IMAGINARY VALUES OF THE GIVEN COMPLEX NUMBERS.
// THEN USING THE REAL AND IMAGINARY VALUES USE THE GIVEN FORMULA TO RETRIEVE THE REAL AND IMAGINARY VALUES OF
// THE RESULTING COMPLEX NUMBER.

char * complexNumberMultiply(char * num1, char * num2)
{
    int r1,r2,i1,i2;
    
    // USING THE SSCANF FUNCTION TO RETRIEVE THE REAL AND IMAGINARY VALUES.
    sscanf(num1,"%d+%di",&r1,&i1);
    sscanf(num2,"%d+%di",&r2,&i2);
    
    int r = (r1*r2)-(i1*i2);
    int i = (r1*i2)+(r2*i1);
    
    char* ans = (char*)malloc(sizeof(char)*101);
    
    sprintf(ans,"%d+%di",r,i);
    
    return ans;
}

// TIME COMPLEXITY : O(1)
// SPACE COMPLEXITY : O(N) SINCE THE LENGTH OF THE ANS STRING DEPENDS UPON THE LENGTH OF THE GIVEN COMPLEX NUMBERS.
