// THE PROBLEM STATEMENT IS TO COUNT THE NUMBER OF ODD ELEMENTS BETWEEN THE RANGE.

// NAIVE APPROACH IS TO TRAVERSE THE LOOP FROM LOW TO HIGH AND CHECK IF IT IS AN ODD NUMBER IF IT IS THEN INCREMENT THE COUNT.

// BUT THE OPTIMAL SOLUTION IS TO VIEW IT AS AN MATHEMATICAL PROBLEM, SINCE ODD AND EVEN NUMBERS REOCCUR IN A UNIFORM MANNER,
// SO IF BOTH THE LOW AND HIGH IS EVEN OR ODD, THEN THE NUMBER OF ELEMENTS IS ODD ELSE IT IS EVEN. IF BOTH ARE EVEN THEN THE COUNT OF ODD NUMBERS IS NUMBER OF ELEMENTS DIVIDE BY 2
// ELSE IF BOTH ARE ODD THEN THE COUNT OF ODD NUMBERS IS NUMBER OF ELEMENTS DIVIDE BY 2 PLUS ONE.
// ELSE THE COUNT OF ODD NUMBERS IS NUMBER OF ELEMENTS DIVIDE BY 2.

int countOdds(int low, int high)
{
    int countOfOddNumbers = 0,numberOfElements = ((high-low)+1);
    
    if(low%2 == 0 && high%2 == 0)
    {
        countOfOddNumbers = numberOfElements/2;
    }
    else if(low%2 != 0 && high%2 != 0)
    {
        countOfOddNumbers = (numberOfElements/2)+1;
    }
    else
    {
        countOfOddNumbers = numberOfElements/2;
    }
    
    return countOfOddNumbers;
}

// TIME COMPLEXITY : O(1)
// SPACE COMPLEXITY : O(1)
