// THE PROBLEM STATEMENT IS TO RETURN THE NUMBER SEGMENTS IN THE GIVEN STRING. IN OTHER WORDS, THE PROBLEM STATEMENT IS TO RETURN THE NUMBER
// OF WORDS IN THE GIVEN STRING.

// MY APPROACH IS TO USE THE STRTOK FUNCTION IN C TO SPLIT THE GIVEN STRING WITH RESPECT TO A SPACED CHARACTER AND THEN COUNT THE NUMBER 
// OF WORDS IN THE STRING.

int countSegments(char * s)
{
    int ans = 0;
    // APPLYING THE STRTOK FUNCTION.
    char* words = strtok(s," ");
    
    while(words!=NULL)
    {
        ans+=1;
        words = strtok(NULL," ");
    }
    
    return ans;
}

// TIME COMPLEXITY : O(N) WHERE N IS THE NUMBER OF CHARACTERS IN THE STRING.
// SPACE COMPLEXITY : O(1)
