// THE PROBLEM STATEMENT IS TO RETURN THE NUMBER OF STEPS IT TAKES TO WATER EACH PLANT IN THE GARDEN. THERE IS A RIVER AT INDEX -1. THE CAPACITY
// OF THE WATERING CAN AND THE CAPACITY OF WATER REQUIRED BY EACH PLANTS IS GIVEN. THE STEP COUNT IS MEASURED BY THE GARDENER'S MOVEMENTS,
// THE GARDENER IS INITIALLY AT INDEX -1, THE GARDENER CAN MOVE EITHER TO THE SUCCESSIVE INDEX OR THE PREVIOUS INDEX WHICH DEFINES A SINGLE STEP.
// IF THE WATERING CAN BECOMES EMPTY, THE GARDENER CAN REFILL THE WATERING CAN IN THE RIVER.

// MY APPROACH IS TO TRAVERSE THE GIVEN PLANTS ARRAY, WHILE TRAVERSING IF THE CURRENT CAPACITY IN THE WATERING CAN IS LESS THAN THE CAPACITY
// NEEDED THEN INCREMENT THE VALUE OF ANSWER BY TWICE THE VALUE OF CURRENT INDEX PLUS ONE ELSE INCREMENT THE VALUE OF ANSWER BY ONE AND THEN UPDATE THE
// WATERING CAN'S CAPACITY ACCORDINGLY. BECAUSE IF THE WATERING CAN'S CAPACITY IS LOW, THE GARDENER HAS TO GO TO THE RIVER TO REFILL IT.

int wateringPlants(int* plants, int plantsSize, int capacity)
{
    int cc = capacity,ans = 0;
    // TRAVERSING THE GIVEN PLANTS ARRAY.
    for(int i=0;i<plantsSize;i++)
    {
        if(cc >= plants[i])
        {
            ans += 1;
            cc -= plants[i];
        }
        else
        {
            ans += ((i*2)+1);
            cc = capacity-plants[i];
        }
    }
    
    return ans;
}

// TIME COMPLEXITY : O(N)
// SPACE COMPLEXITY : O(1)
