// THE PROBLEM STATEMENT IS TO RETURN BITWISE XOR OF ALL THE ELEMENTS OF NUMS. THE NUMS ARRAY OF LENGTH N CONTAINS INTEGERS FROM START AND AT EACH INDEX INCREMENTED BY 2.
// I.E IF N = 5, START = 0, THEN THE NUMS ARRAY WILL LOOK LIKE NUMS = [0,2,4,6,8] AND THE RETURNED VALUE IS 8.

// MY APPROACH IS TO TRAVERS FROM 0 TO N-1, AT EACH ITERATION XOR THE START VALUE TO THE ANS VARIABLE AND INCREMENT THE VALUE OF START BY 2.

int xorOperation(int n, int start)
{
    int ans = 0;
    
    // TRAVERSING FROM 0 TO N-1.
    for(int i=0;i<n;i++)
    {
        ans = ans^start;
        start += 2;
    }
    
    return ans;
}

// TIME COMPLEXITY : O(N)
// SPACE COMPLEXITY : O(1)
